site_name: TER Project

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Passer au mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Passer au mode automatique
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Documentation:
    - Séquence de boot: docs/boot_sequence.md
    - Les Devices Tree: docs/device_tree.md
    - FPGA Manager: docs/fpga_manager.md
    - Projets:
      - Linux - Zybo Z7-20: docs/linux_zybo.md
      - PmodENC - VHDL personnalisé: docs/pmodenc_vhdl.md
      - PmodENC - Baremetal application: docs/pmodenc_baremetal.md
      - PmodENC - Bloc IP personnalisé: docs/pmodenc_ip.md
      - WIP PmodENC - Linux application: docs/pmodenc_linux.md
    - Rappels:
      - Activation SSH: docs/ssh_activation.md
  - Journal de bord:
    - Semaine 1: journal/semaine1.md
    - Semaine 2: journal/semaine2.md
    - Semaine 3: journal/semaine3.md
    - Semaine 4: journal/semaine4.md
    - Semaine 5: journal/semaine5.md
    - Semaine 6: journal/semaine6.md
    

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.arithmatex
  - attr_list
  - md_in_html
  - abbr

extra: 
  generator: false

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TER-Zybo

copyright: |
  &copy; 2024 <a href="https://github.com/HDwayne"  target="_blank" rel="noopener">Dwayne HERZBERG</a>,
  <a href="https://github.com/Luxrafen0"  target="_blank" rel="noopener">Oleg PAILLOT</a>.

repo_url: https://github.com/TER-Zybo/Documentations
repo_name: Documentations
